# Generated by Django 5.0.1 on 2024-02-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("PR", "Proposal"),
                    ("PL", "Planning"),
                    ("SC", "Scheduled"),
                    ("CO", "Completed"),
                    ("AR", "Archived"),
                    ("DN", "Denied"),
                    ("RM", "Removed"),
                ],
                default="PR",
                max_length=2,
            ),
        ),
    ]
