# Generated by Django 5.0.1 on 2024-02-20 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="upvotes",
            field=models.ManyToManyField(
                null=True, related_name="up_votes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
