# Generated by Django 5.0.1 on 2024-05-09 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_upvotes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="required_num_upvotes",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="event",
            name="upvotes",
            field=models.ManyToManyField(
                related_name="up_votes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
