# Generated by Django 6.0.2 on 2026-05-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_remove_plan_volunteers_event_date_confirmed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="open_date_proposals",
            field=models.BooleanField(default=False),
        ),
    ]
