# Generated by Django 5.0.1 on 2024-02-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name_first",
            field=models.CharField(default="test", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="name_last",
            field=models.CharField(default="last", max_length=30),
            preserve_default=False,
        ),
    ]
