# Generated by Django 5.0.1 on 2024-02-20 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0002_user_name_first_user_name_last"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name_first",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name_last",
        ),
    ]
