# Generated by Django 6.0.2 on 2026-02-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0004_alter_user_email_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_event_reminders",
            field=models.BooleanField(
                default=True,
                help_text="Receive reminder emails 24 hours before events you committed to attend.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_status_updates",
            field=models.BooleanField(
                default=True,
                help_text="Receive emails when events you upvoted or committed to change status.",
            ),
        ),
    ]
