# Generated by Django 6.0.2 on 2026-05-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0005_add_email_notification_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default.jpg",
                upload_to="profile_picture/",
            ),
        ),
    ]
