# Generated by Django 6.0.2 on 2026-02-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventstatuschange",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
